### ISSUE TITLE
Add food-items for different meals

### ISSUE THREAD

**Issue by aditimithal** [danish-goel/Fettle#25]
For all breakfast, lunch &  dinner, different meals have to be added

**Comment by manangakhar** [comment]
https://github.com/danish-goel/Fettle/blob/master/app/src/main/java/fettle/iiitd/com/fettle/Activities/AddFoodActivity.java
@aditimithal 
modify this file for breakfastDishIds, lunchDishIds, dinnerDishIds (present around line 50) for the objectIds.
