### ISSUE TITLE
user inputs to be shown in profile

### ISSUE THREAD

**Issue by aditimithal** [danish-goel/Fettle#42]
they include: bmi, type of lifestyle, gender, target weight..

**Comment by manangakhar** [comment]
need screens

**Comment by manangakhar** [comment]
functions added in User class

**Comment by danish-goel** [comment]
@MnnGkhr gender,target weight are already there.Do we really need to input bmi?we can calculate that on our own based on height and weight.

**Comment by manangakhar** [comment]
She means that we need to show them in profile info... 
And lifestyle is activeness. 
User mein static functions bane huey hain. 
Mainly UI ka kaam hai, ki kahan test views daalne hain.

**Comment by thecoldviews** [comment]
Danish phone number bol koi jispe tu reachable ho and telegram dekh. :P

Regards,
_Sarthak Ahuja *[image: Behance] https://www.behance.net/sarthakahuja
*CS Undergrad, IIIT Delhi_ _|_ _2012088 *
*+91 9971496664 | sarthak12088@iiitd.ac.in sarthak12088@iiitd.ac.in_

**Comment by danish-goel** [comment]
8800449069

**Comment by manangakhar** [comment]
@danish-goel 
u know that ur repo is public, along with ur phone number ;) :P
?

**Comment by aditimithal** [comment]
Hahahhahahahhahhahah :'D

On Sun, Apr 17, 2016 at 8:56 PM, Manan Gakhar notifications@github.com
wrote:

> @danish-goel https://github.com/danish-goel
> u know that ur repo is public, along with ur phone number ;) :P
> ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/danish-goel/Fettle/issues/42#issuecomment-211044002

## 

Regards
Aditi Mithal

**Comment by danish-goel** [comment]
@MnnGkhr reopen kyun kiya?

**Comment by manangakhar** [comment]
@danish-goel 
to make sure u remove ur phone number :P
