### ISSUE TITLE
Add text on FAB

### ISSUE THREAD

**Issue by thecoldviews** [danish-goel/Fettle#9]
Add - "Fast Food", "Regular Food"

**Comment by manangakhar** [comment]
@danish-goel 
having issues, see it once
https://github.com/Clans/FloatingActionButton

**Comment by danish-goel** [comment]
tried setting it in layout as well as programmatically but none seem to work

**Comment by danish-goel** [comment]
Done 7bf77d9424ffc272cfd376d3a8ab7c1326e75013
